website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager
import sqlite3

db = SQLAlchemy()

BASE_DIR = path.dirname(path.abspath(__file__))
DB_PATH = path.join(BASE_DIR, "database.db")

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = "STUDENT MANAGEMENT APPLICATION"
    app.config['SQLALCHEMY_DATABASE_URI'] = f"sqlite:///{DB_PATH}"

    db.init_app(app)

    from .model import User, Marks
    from .views import views 
    from .auth import auth
    
    app.register_blueprint(views, url_prefix = "/")
    app.register_blueprint(auth, url_prefix = "/")

    create_database(app)
    admin()

    login_manager = LoginManager()
    login_manager.login_view = "auth.login" 
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(email):
        return User.query.get(email)

    return app

def create_database(app):
    if not path.exists(DB_PATH):
        with app.app_context():
            db.create_all()


def admin():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()

    # Execute the INSERT query
    c.execute("INSERT OR IGNORE INTO User (email, password, first_name, role) VALUES ('admin@gmail.com', 'admin123', 'Admin', 'admin')")

    # Commit the changes and close the connection
    conn.commit()
    conn.close()

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from . import db
from flask_login import login_user, login_required, logout_user, current_user
from .model import User
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint('auth', __name__)

@auth.route("/signup",methods=["GET",'POST'])
def signup():
    if request.method == "POST":
        email = request.form.get("email")
        first_name = request.form.get("firstName")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")

        user = User.query.filter_by(email = email).first()
        if email == "admin@gmail.com":
            flash("This is a Email for Admin Sign As Student try another email",category="error")
        elif user:
            flash("Email Already exist", category='error')
        elif len(email) < 4:  
            flash("Email must be greater than 4 characters", category="error")
        elif len(first_name) < 2:  
            flash("Name must be at least 4 characters", category="error")
        elif password1 != password2:
            flash("Entered password incorrectly type again", category="error")
        elif len(password1) < 7:  
            flash("password length must be at least 7 characters", category="error")
        else:
            new_user = User(email = email, password = generate_password_hash(password1, method='scrypt'), first_name = first_name)
            db.session.add(new_user)
            db.session.commit()
            flash("Account Created Successfully!!!", category="success")
            login_user(new_user)
            return redirect(url_for('views.student'))
    return render_template("signup.html",user = current_user)


@auth.route("/",methods=['GET','POST'])
def login():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")
        user = User.query.filter_by(email=email).first()
        if user:
            if user.email == "admin@gmail.com" and user.password =="admin123":
                flash("Logged in Successfully as Admin", category="success")
                login_user(user)
                return redirect(url_for("views.admin"))

            elif check_password_hash(user.password,password):
                flash("Logged in Successfully", category="success")
                login_user(user)
                return redirect(url_for("views.student"))     
               
    return render_template("login.html", user = current_user)


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))

website/views.py
from flask import redirect,url_for,request,flash
from flask import Blueprint,render_template
from flask_login import login_required, current_user
from .model import Marks, User
from . import db, DB_PATH
import sqlite3
 
views = Blueprint('views', __name__)


@views.route("/student")
@login_required
def student():
    try :
        marks_list = Marks.query.filter_by(email=current_user.email).first()
        mark_values = [marks_list.mark1, marks_list.mark2, marks_list.mark3, marks_list.mark4, marks_list.mark5]
    except :
        mark_values=[0,0,0,0,0]
    return render_template("student.html",user = current_user,mark_values = mark_values)


@views.route("/admin",methods=['GET','POST'])
@login_required
def admin():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()

    insert_table_data = c.execute("""SELECT first_name, email FROM user WHERE email NOT IN (SELECT email FROM marks) AND id != (SELECT MIN(id) FROM user)""")
    insert_table_data = insert_table_data.fetchall()


    update_table_data = c.execute("""SELECT email,name,mark1,mark2,mark3,mark4,mark5 FROM marks """)
    update_table_data = update_table_data.fetchall()

    delete_table_data = c.execute("SELECT first_name, email FROM user WHERE id NOT IN (SELECT MIN(id) FROM user)")
    delete_table_data = delete_table_data.fetchall()

    return render_template("admin.html",user = current_user, insert_table_data = insert_table_data,update_table_data = update_table_data,delete_table_data = delete_table_data)


@views.route("/insert",methods=['POST'])
@login_required
def insert_data():
    if request.method == "POST":
        name = request.form.get("name")
        email = request.form.get("email")
        mark1 = request.form.get("mark1")
        mark2 = request.form.get("mark2")
        mark3 = request.form.get("mark3")
        mark4 = request.form.get("mark4")
        mark5 = request.form.get("mark5")
        value = Marks(email = email,name = name,mark1=mark1,mark2=mark2,mark3=mark3,mark4=mark4,mark5=mark5)
        db.session.add(value)
        db.session.commit()
    return redirect(url_for("views.admin"))


@views.route("/update",methods=['POST'])
@login_required
def update_data():
    if request.method == "POST":
        name = request.form.get('name')
        email = request.form.get('email')
        mark_select = request.form.get('markSelect')
        mark_value = request.form.get('markValue')
        marks = Marks.query.filter_by(email=email).first()

    # Update the record with new values
        if mark_select == 'mark1':
            marks.mark1 = mark_value
        elif mark_select == 'mark2':
            marks.mark2 = mark_value
        elif mark_select == 'mark3':
            marks.mark3 = mark_value
        elif mark_select == 'mark4':
            marks.mark4 = mark_value
        elif mark_select == 'mark5':
            marks.mark5 = mark_value

        # Commit the changes to the database
        db.session.commit()

        flash("data is Updated successfuly",category="success")
        return redirect(url_for("views.admin"))


@views.route("/delete",methods=['POST'])
@login_required
def delete_data():
    if request.method == "POST":
        email = request.form.get('email')

        # Retrieve the user to delete from the database
        user = User.query.filter_by(email=email).first()
        user_marks = Marks.query.filter_by(email=email).first()

        # Check if the user exists
        if user:
            # Delete the user
            db.session.delete(user)
            db.session.commit()
        if user_marks:
            # Delete the user
            db.session.delete(user_marks)
            db.session.commit()
    return redirect(url_for("views.admin"))

website/templates/admin.html
{% extends "base.html" %}

{% block title %}Admin Page{%endblock%}

{% block content %}

    <div class="container">
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" href="#collapse1">Data Insertion Form</a>
                    </h4>
                </div>
                <div id="collapse1" class="panel-collapse collapse">
                    <h3 align="center">Student Data Insertion Form</h3>
                    <br />
                    <div class="container">
                        <table class="table table-bordered" style="width: 100%; max-width: 900px; margin-left: auto; margin-right: auto;">
                            <thead>
                                <tr>
                                    <th>Firstname</th>
                                    <th>Email</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for row in insert_table_data %}
                                <tr>
                                    <td>{{ row[0] }}</td>
                                    <td>{{ row[1] }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <form method="POST" action="{{ url_for('views.insert_data') }}">
                        <div class="form-group"
                            style="width: 100%; max-width: 900px; margin-left: auto; margin-right: auto;">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" id="name" name="name" placeholder="Enter name" />
                        </div>
                        <br />
                        <div class="form-group"
                            style="width: 100%; max-width: 900px; margin-left: auto; margin-right: auto;">
                            <label for="email">Email Address</label>
                            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" />
                        </div>
                        <br />
                        <div class="form-group"
                            style="width: 100%; max-width: 900px; margin-left: auto; margin-right: auto;">
                            <label for="mark1">Mark 1</label>
                            <input type="number" class="form-control" id="mark1" name="mark1" placeholder="Enter mark 1" />
                        </div>
                        <br />
                        <div class="form-group"
                            style="width: 100%; max-width: 900px; margin-left: auto; margin-right: auto;">
                            <label for="mark2">Mark 2</label>
                            <input type="number" class="form-control" id="mark2" name="mark2" placeholder="Enter mark 2" />
                        </div>
                        <br />
                        <div class="form-group"
                            style="width: 100%; max-width: 900px; margin-left: auto; margin-right: auto;">
                            <label for="mark3">Mark 3</label>
                            <input type="number" class="form-control" id="mark3" name="mark3" placeholder="Enter mark 3" />
                        </div>
                        <br />
                        <div class="form-group"
                            style="width: 100%; max-width: 900px; margin-left: auto; margin-right: auto;">
                            <label for="mark4">Mark 4</label>
                            <input type="number" class="form-control" id="mark4" name="mark4" placeholder="Enter mark 4" />
                        </div>
                        <br />
                        <div class="form-group"
                            style="width: 100%; max-width: 900px; margin-left: auto; margin-right: auto;">
                            <label for="mark5">Mark 5</label>
                            <input type="number" class="form-control" id="mark5" name="mark5" placeholder="Enter mark 5" />
                        </div>
                        <div class="text-center" style="padding-bottom: 15px;">
                            <button type="submit" class="btn btn-primary"
                                style="width: 100%; max-width: 900px; margin-left: auto; margin-right: auto;">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" href="#collapse2">Data Updation Form</a>
                    </h4>
                </div>
                <div id="collapse2" class="panel-collapse collapse">
                    <h3 align="center">Student Data Updation Form</h3>
                    <br />
                    <div class="container">
                    <table class="table table-bordered" style="width: 100%; max-width: 900px; margin-left: auto; margin-right: auto;">
                            <thead>
                                <tr>
                                    <th>Email</th>
                                    <th>Firstname</th>
                                    <th>Mark 1</th>
                                    <th>Mark 2</th>
                                    <th>Mark 3</th>
                                    <th>Mark 4</th>
                                    <th>Mark 5</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for row in update_table_data %}
                                <tr>
                                    <td>{{ row[0] }}</td>
                                    <td>{{ row[1] }}</td>
                                    <td>{{ row[2] }}</td>
                                    <td>{{ row[3] }}</td>
                                    <td>{{ row[4] }}</td>
                                    <td>{{ row[5] }}</td>
                                    <td>{{ row[6] }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <form method="POST" action="{{ url_for('views.update_data') }}">
                        <br />
                        <h3 align="center">Student Data Updation Form</h3>
                        <div class="form-group"
                            style="width: 100%; max-width: 900px; margin-left: auto; margin-right: auto;">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" id="name" name="name" placeholder="Enter name" />
                        </div>
                        <br />
                        <div class="form-group"
                            style="width: 100%; max-width: 900px; margin-left: auto; margin-right: auto;">
                            <label for="email">Email Address</label>
                            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" />
                        </div>
                        <br />
                        <div class="form-group"
                            style="width: 100%; max-width: 900px; margin-left: auto; margin-right: auto;">
                            <label for="markSelect">Select Mark</label>
                            <select class="form-control" id="markSelect" name="markSelect">
                                <option value="mark1">Mark 1</option>
                                <option value="mark2">Mark 2</option>
                                <option value="mark3">Mark 3</option>
                                <option value="mark4">Mark 4</option>
                                <option value="mark5">Mark 5</option>
                            </select>
                        </div>
                        <br />
                        <div class="form-group"
                            style="width: 100%; max-width: 900px; margin-left: auto; margin-right: auto;">
                            <label for="markValue">Mark Value</label>
                            <input type="number" class="form-control" id="markValue" name="markValue"
                                placeholder="Enter mark value" />
                        </div>
                        <div class="text-center" style="padding-bottom: 15px;">
                            <button type="submit" class="btn btn-primary"
                                style="width: 100%; max-width: 900px; margin-left: auto; margin-right: auto;">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" href="#collapse3">Data Deletion Form</a>
                    </h4>
                </div>
                <div id="collapse3" class="panel-collapse collapse">
                    <h3 align="center">Student Deletion Form</h3>
                    <br />
                    <form method="POST" action="{{ url_for('views.delete_data') }}">
                        <br />
                        <h3 align="center">Student Data Deletion Form</h3>
                        <div class="container">
                            <table class="table table-bordered" style="width: 100%; max-width: 900px; margin-left: auto; margin-right: auto;">
                            <thead>
                                <tr>
                                    <th>Firstname</th>
                                    <th>Email</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for row in delete_table_data %}
                                <tr>
                                    <td>{{ row[0] }}</td>
                                    <td>{{ row[1] }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                            </table>
                        </div> 
                        <div class="form-group"
                            style="width: 100%; max-width: 900px; margin-left: auto; margin-right: auto;">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" id="name" name="name" placeholder="Enter name" />
                        </div>
                        <br />
                        <div class="form-group"
                            style="width: 100%; max-width: 900px; margin-left: auto; margin-right: auto;">
                            <label for="email">Email Address</label>
                            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" />
                        </div>
                        <div class="text-center" style="padding-bottom: 15px;">
                            <input type="submit" class="btn btn-primary" value ="delete"
                                style="width: 100%; max-width: 900px; margin-left: auto; margin-right: auto">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{%endblock%}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>

          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

    <title>{% block title %} {%endblock%}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #000000">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                  {% if user.is_authenticated %}
                    {% if user.role == "student" %}
                      <li class="nav-item">
                          <a class="nav-link" href="/student">Student Content Page</a>
                      </li>
                    {% elif user.role == "admin" %}
                    <li class="nav-item">
                        <a class="nav-link" href="/admin">Admin Content Page</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="/logout">Logout</a>
                    </li>
                  {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/signup">Signup</a>
                    </li>
                  {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    
    {% with messages = get_flashed_messages(with_categories = true) %}
      {% if messages%}
        {% for category, message in messages %}
         {% if category == "error" %}
            <div class = "alert alert-danger alert-dismissible fade show" role="alert">
              {{message}}
              <button type="button" class="close" data-dismiss="alert">
                <span> &times; </span>
              </button>
            </div>
          {% else %}
            <div class = "alert alert-success alert-dismissible fade show" role="alert">
              {{message}}
              <button type="button" class="close" data-dismiss="alert">
                <span> &times; </span>
              </button>
            </div>
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endwith %}
    <div class="container">

    {%block content %}
    {%endblock%}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>
</html>

website/templates/login.html
{% extends "base.html" %}

{% block title %}Login Page{%endblock%}

{% block content %}
<div class="container">
  <form method="POST">
    <br />
    <h3 align="center">Login</h3>
    <div class="form-group">
      <label for="email">Email Address</label>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        placeholder="Enter email"
      />
    </div>
    <br>
    <div class="form-group">
      <label for="password">Password</label>
      <input
        type="password"
        class="form-control"
        id="password"
        name="password"
        placeholder="Enter password"
      />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Login</button>
  </form>
  <br>
  {{value}}
  <h4>To Login as Admin Type (Email as "admin@gmail.com" and Password as "admin123")</h4>
</div>
{% endblock %}

website/templates/signup.html
{% extends "base.html" %}

{% block title %}SignUp Page{%endblock%}

{%block content%}
<div class="container">
    <form method="POST">
        <br>
        <h3 align="center">Sign Up</h3>
        <div class="form-group">
            <label for="email">Email Address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">

        </div>
        <br>
        <div class="form-group">
            <label for="firstName">First Name</label>
            <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Enter Name">
        </div>
        <br>
        <div class="form-group">
            <label for="password1">Password</label>
            <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter password">

        </div>
        <br>
        <div class="form-group">
            <label for="password2">Enter Password again</label>
            <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm Password">
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
<br>
<div class="container">
    <p> 1. The password must be Atleast 7 characters and Email id must be Unique</p>
    <p> 2. The Email id 'admin@gmail.com' is not Usable. By default this is set for the Admin </p>
</div>
{% endblock %}

website/templates/student.html
{% extends "base.html" %}

{% block title %}Student Page{%endblock%}

{% block content %}
<center>
<canvas id="myChart" style="width:5%;max-width:1050px;"></canvas>
    <script>
      var xValues = ["Mark1", "Mark2", "Mark3", "Mark4", "Mark5"];
      var yValues = {{mark_values}};
      var barColors = ["red", "green", "blue", "orange", "brown"];

      new Chart("myChart", {
        type: "bar",
        data: {
          labels: xValues,
          datasets: [{
            backgroundColor: barColors,
            data: yValues
          }]
        },
        options: {
          legend: { display: false },
          title: {
            display: true,
            text: "World Wine Production 2018"
          },
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: true,
                suggestedMin: 0,
                suggestedMax: 100
              }
            }]
          }
        }
      });
    </script>
</center>
{%endblock%}